### ISSUE TITLE
Concurrent map write / read / iteration

### ISSUE THREAD

**Issue by alok87** [practo/k8s-worker-pod-autoscaler#17]
Find and fix the race.

WPA controller is crashing sometimes because of concurrent map write. Please figure out this issue and fix it.

```
fatal error: I0812 07:42:08.440000       1 controller.go:299] queue: XXX-XXX-XX, messages: 0, idle: -1, desired: 0
concurrent map iteration and map write

goroutine 16 [running]:
runtime.throw(0x170f0aa, 0x26)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc00009ad58 sp=0xc00009ad28 pc=0x42c042
runtime.mapiternext(0xc00009af60)
	/usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc00009ade0 sp=0xc00009ad58 pc=0x40ebe7
github.com/practo/k8s-worker-pod-autoscaler/pkg/queue.(*Poller).Run(0xc00043e270, 0xc000088660)
	/src/pkg/queue/poller.go:90 +0xfc fp=0xc00009afd0 sp=0xc00009ade0 pc=0x13ec58c
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00009afd8 sp=0xc00009afd0 pc=0x458671
created by main.(*runCmd).run
	/src/cmd/workerpodautoscaler/run.go:121 +0x718

goroutine 1 [chan receive, 116 minutes]:
github.com/practo/k8s-worker-pod-autoscaler/pkg/controller.(*Controller).Run(0xc00043af00, 0xa, 0xc000088660, 0x0, 0x0)
	/src/pkg/controller/controller.go:154 +0x2eb
main.(*runCmd).run(0xc0001a56c0, 0xc000328500, 0xc000203cc0, 0x0, 0x5)
	/src/cmd/workerpodautoscaler/run.go:139 +0x974
github.com/spf13/cobra.(*Command).execute(0xc000328500, 0xc000203c70, 0x5, 0x5, 0xc000328500, 0xc000203c70)
	/src/vendor/github.com/spf13/cobra/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x26e96a0, 0xc0002aff78, 0x2, 0x2)
	/src/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/src/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/src/cmd/workerpodautoscaler/main.go:42 +0xcd

goroutine 5 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x26fbb40)
	/src/vendor/k8s.io/klog/klog.go:990 +0x8b
created by k8s.io/klog.init.0
	/src/vendor/k8s.io/klog/klog.go:404 +0x6c

goroutine 6 [syscall, 116 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 8 [chan receive, 116 minutes]:
github.com/practo/k8s-worker-pod-autoscaler/pkg/signals.SetupSignalHandler.func1(0xc00020dbc0, 0xc000088660)
	/src/pkg/signals/signal.go:20 +0x34
created by github.com/practo/k8s-worker-pod-autoscaler/pkg/signals.SetupSignalHandler
	/src/pkg/signals/signal.go:19 +0xd0

goroutine 48 [sleep]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:307
time.Sleep(0x7708828c)
	/usr/local/go/src/runtime/time.go:105 +0x159
k8s.io/client-go/util/flowcontrol.realClock.Sleep(...)
	/src/vendor/k8s.io/client-go/util/flowcontrol/throttle.go:70
k8s.io/client-go/util/flowcontrol.(*tokenBucketRateLimiter).Accept(0xc0003704c0)
	/src/vendor/k8s.io/client-go/util/flowcontrol/throttle.go:95 +0x132
k8s.io/client-go/rest.(*Request).tryThrottle(0xc001062300, 0xc00102d1e0, 0x2c7)
	/src/vendor/k8s.io/client-go/rest/request.go:534 +0x2a8
k8s.io/client-go/rest.(*Request).Do(0xc001062300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/src/vendor/k8s.io/client-go/rest/request.go:823 +0x62
github.com/practo/k8s-worker-pod-autoscaler/pkg/generated/clientset/versioned/typed/workerpodautoscaler/v1alpha1.(*workerPodAutoScalers).Update(0xc001356360, 0xc00102d080, 0xc, 0x1a1bb40, 0xc001356360)
	/src/pkg/generated/clientset/versioned/typed/workerpodautoscaler/v1alpha1/workerpodautoscaler.go:131 +0x10a
github.com/practo/k8s-worker-pod-autoscaler/pkg/controller.(*Controller).updateWorkerPodAutoScalerStatus(0xc00043af00, 0xc000000001, 0xc00126d340, 0x100000001, 0xc000dd3ce0, 0x4)
	/src/pkg/controller/controller.go:413 +0xb5
github.com/practo/k8s-worker-pod-autoscaler/pkg/controller.(*Controller).syncHandler(0xc00043af00, 0xc000b81920, 0x2d, 0x16ecd35, 0x6, 0xc000dd3d98, 0x42adbf)
	/src/pkg/controller/controller.go:307 +0x9f1
github.com/practo/k8s-worker-pod-autoscaler/pkg/controller.(*Controller).processNextWorkItem.func1(0xc00043af00, 0x15aff80, 0xc0013752e0, 0x0, 0x0)
	/src/pkg/controller/controller.go:204 +0x13f
github.com/practo/k8s-worker-pod-autoscaler/pkg/controller.(*Controller).processNextWorkItem(0xc00043af00, 0xc000924801)
	/src/pkg/controller/controller.go:214 +0x4d
github.com/practo/k8s-worker-pod-autoscaler/pkg/controller.(*Controller).runWorker(0xc00043af00)
	/src/pkg/controller/controller.go:164 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00087cd40)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00087cd40, 0x3b9aca00, 0x0, 0xc0003b4701, 0xc000088660)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00087cd40, 0x3b9aca00, 0xc000088660)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/practo/k8s-worker-pod-autoscaler/pkg/controller.(*Controller).Run
	/src/pkg/controller/controller.go:152 +0x262

goroutine 23 [chan receive, 116 minutes]:
k8s.io/client-go/tools/cache.(*sharedProcessor).run(0xc000327c00, 0xc0003e81e0)
	/src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:478 +0x46
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:54 +0x2e
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0003b45c0, 0xc0000b69c0)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62

goroutine 19 [IO wait]:
internal/poll.runtime_pollWait(0x7f4f62f6fea8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00039c218, 0x72, 0xf400, 0xf42d, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00039c200, 0xc0002a0000, 0xf42d, 0xf42d, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00039c200, 0xc0002a0000, 0xf42d, 0xf42d, 0x203000, 0x0, 0xf3f6)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000ed88, 0xc0002a0000, 0xf42d, 0xf42d, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc000fddb40, 0xc0002a0000, 0xf42d, 0xf42d, 0xc001264a08, 0x441bd2, 0xc0012649e0)
	/usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc00037acd8, 0x19c6c20, 0xc000fddb40, 0x409995, 0x1561ee0, 0x16937c0)
	/usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc00037aa80, 0x19c8500, 0xc00000ed88, 0x5, 0xc00000ed88, 0x2ae)
	/usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc00037aa80, 0x1787c00, 0xc00037abb8, 0xc001264d58)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc00037aa80, 0xc0003fd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1236 +0x137
bufio.(*Reader).Read(0xc0000b4420, 0xc0003cc1f8, 0x9, 0x9, 0x4063f4, 0xc000d286c0, 0xc001264d58)
	/usr/local/go/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x19c6ae0, 0xc0000b4420, 0xc0003cc1f8, 0x9, 0x9, 0x9, 0x19c6dc0, 0xc0007c9d30, 0xc000048050)
	/usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc0003cc1f8, 0x9, 0x9, 0x19c6ae0, 0xc0000b4420, 0x0, 0x0, 0x0, 0x0)
	/src/vendor/golang.org/x/net/http2/frame.go:237 +0x88
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0003cc1c0, 0xc000667dd0, 0x0, 0x0, 0x0)
	/src/vendor/golang.org/x/net/http2/frame.go:492 +0xa1
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc001264fb8, 0x1786998, 0xc000058fb8)
	/src/vendor/golang.org/x/net/http2/transport.go:1679 +0x8d
golang.org/x/net/http2.(*ClientConn).readLoop(0xc0000bc480)
	/src/vendor/golang.org/x/net/http2/transport.go:1607 +0x76
created by golang.org/x/net/http2.(*Transport).newClientConn
	/src/vendor/golang.org/x/net/http2/transport.go:670 +0x637

goroutine 21 [select]:
github.com/practo/k8s-worker-pod-autoscaler/pkg/queue.(*Poller).sync(0xc00043e270, 0xc000088660)
	/src/pkg/queue/poller.go:61 +0x1ae
created by github.com/practo/k8s-worker-pod-autoscaler/pkg/queue.(*Poller).Run
	/src/pkg/queue/poller.go:80 +0x64

goroutine 14 [select]:
github.com/practo/k8s-worker-pod-autoscaler/pkg/queue.(*Queues).Sync(0xc000433ef0, 0xc000088660)
	/src/pkg/queue/queue.go:68 +0x19d
created by main.(*runCmd).run
	/src/cmd/workerpodautoscaler/run.go:110 +0x3ec

```

**Comment by alok87** [comment]
One more
```
fatal error: concurrent map read and map write

goroutine 63 [running]:
runtime.throw(0x17095bf, 0x21)
        /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0019e7930 sp=0xc0019e7900 pc=0x42c042
runtime.mapaccess1_faststr(0x1523640, 0xc0004642d0, 0xc0005e3100, 0x34, 0xc0014a82f8)
        /usr/local/go/src/runtime/map_faststr.go:21 +0x469 fp=0xc0019e79a0 sp=0xc0019e7930 pc=0x412249
github.com/practo/k8s-worker-pod-autoscaler/pkg/queue.(*Queues).ListQueue(...)
        /src/pkg/queue/queue.go:162
github.com/practo/k8s-worker-pod-autoscaler/pkg/queue.(*Queues).listQueueByNamespace(...)
        /src/pkg/queue/queue.go:166
github.com/practo/k8s-worker-pod-autoscaler/pkg/queue.(*Queues).Add(0xc000464300, 0xc0005e2fc0, 0xc, 0xc0005e2fcd, 0x27, 0xc00115d3b0, 0x64, 0x1, 0x20, 0x0)
        /src/pkg/queue/queue.go:123 +0x5af fp=0xc0019e7ae0 sp=0xc0019e79a0 pc=0x13ed67f
github.com/practo/k8s-worker-pod-autoscaler/pkg/controller.(*Controller).syncHandler(0xc000462c80, 0xc0005e2fc0, 0x34, 0x16ecd35, 0x6, 0xc0019e7d98, 0xc000412710)
        /src/pkg/controller/controller.go:277 +0xbbb fp=0xc0019e7d30 sp=0xc0019e7ae0 pc=0x13f257b
github.com/practo/k8s-worker-pod-autoscaler/pkg/controller.(*Controller).processNextWorkItem.func1(0xc000462c80, 0x15aff80, 0xc0005282e0, 0x0, 0x0)
        /src/pkg/controller/controller.go:204 +0x13f fp=0xc0019e7e38 sp=0xc0019e7d30 pc=0x13f347f
github.com/practo/k8s-worker-pod-autoscaler/pkg/controller.(*Controller).processNextWorkItem(0xc000462c80, 0xc0003c8101)
        /src/pkg/controller/controller.go:214 +0x4d fp=0xc0019e7e70 sp=0xc0019e7e38 pc=0x13f195d
github.com/practo/k8s-worker-pod-autoscaler/pkg/controller.(*Controller).runWorker(0xc000462c80)
        /src/pkg/controller/controller.go:164 +0x2b fp=0xc0019e7e90 sp=0xc0019e7e70 pc=0x13f18eb
github.com/practo/k8s-worker-pod-autoscaler/pkg/controller.(*Controller).runWorker-fm()
        /src/pkg/controller/controller.go:163 +0x2a fp=0xc0019e7ea8 sp=0xc0019e7e90 pc=0x13f3f9a
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0007bd600)
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54 fp=0xc0019e7ee0 sp=0xc0019e7ea8 pc=0x114fe34
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0007bd600, 0x3b9aca00, 0x0, 0x1, 0xc000088660)
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8 fp=0xc0019e7f90 sp=0xc0019e7ee0 pc=0x114f418
k8s.io/apimachinery/pkg/util/wait.Until(0xc0007bd600, 0x3b9aca00, 0xc000088660)
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d fp=0xc0019e7fc8 sp=0xc0019e7f90 pc=0x114f30d
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0019e7fd0 sp=0xc0019e7fc8 pc=0x458671
created by github.com/practo/k8s-worker-pod-autoscaler/pkg/controller.(*Controller).Run
        /src/pkg/controller/controller.go:152 +0x262
```
