### ISSUE TITLE
WPA suffers restart with all go routines crashing

### ISSUE THREAD

**Issue by alok87** [practo/k8s-worker-pod-autoscaler#71]
WPA crashes due to race condition when sleeping for short poll interval.

```
goroutine 71311719 [sleep]:
time.Sleep(0x4a817c800)
	/usr/local/go/src/runtime/time.go:188 +0xba
github.com/practo/k8s-worker-pod-autoscaler/pkg/queue.(*SQS).waitForShortPollInterval(...)
	/src/pkg/queue/sqs.go:372
github.com/practo/k8s-worker-pod-autoscaler/pkg/queue.(*SQS).poll(0xc0001fbc80, 0xc004cddfc0, 0x32, 0xc0062220f6, 0x2a, 0xc00440a440, 0xf, 0xc0062220c0, 0x60, 0xc0062220c8, ...)
	/src/pkg/queue/sqs.go:486 +0x4bf
github.com/practo/k8s-worker-pod-autoscaler/pkg/queue.(*Poller).runPollThread(0xc00019c090, 0xc004cddfc0, 0x32)
	/src/pkg/queue/poller.go:46 +0x88
created by github.com/practo/k8s-worker-pod-autoscaler/pkg/queue.(*Poller).Run
	/src/pkg/queue/poller.go:94 +0x20d
```

**Comment by alok87** [comment]
This could because of the concurrent map write happening. Similar issue was found in beanstalk feature PR https://github.com/practo/k8s-worker-pod-autoscaler/pull/69/commits/81537618688edb07d3d0b0f33c031f6d896c598b

**Comment by alok87** [comment]
Not reproducible after https://github.com/practo/k8s-worker-pod-autoscaler/commit/81537618688edb07d3d0b0f33c031f6d896c598b
